name: doctor_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  firebase_core: any
  cloud_firestore: any
  firebase_auth: ^5.4.1
  logger: ^2.0.2
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^4.10.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/back.png
    - assets/images/data.png
    - assets/images/language.png
    - assets/images/notify.png
    - assets/images/phone.png
    - assets/images/privacy.png
    - assets/images/signout.png
    - assets/images/Question.png
    - assets/images/Picture.png
    - assets/images/Setting.png
    - assets/images/Baby.png
    - assets/images/Robot.png
    - assets/images/Main.png
    - assets/images/pregnancy.png
    - assets/images/happy.png
    - assets/images/sad.png

